{% set name = "gtop" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/gtop/-/gtop-{{ version }}.tgz
  sha256: a8e90b828e33160c6a0ac4fb11231f292496e8049c0dac814e46fdd0c90817c1

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - test -f $PREFIX/bin/gtop  # [unix]

about:
  home: https://github.com/aksakalli/gtop
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: System monitoring dashboard for the terminal

extra:
  recipe-maintainers:
    - matthiasdiener
