{% set name = "gtop" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/gtop/-/gtop-{{ version }}.tgz
  sha256: 5bd04175c5d075b58448cf4fff3a2c6a760e28807e73f4a8f1ab0adf14d7c926

build:
  number: 3

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - test -f $PREFIX/bin/gtop  # [unix]

about:
  home: https://github.com/aksakalli/gtop
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: System monitoring dashboard for the terminal

extra:
  recipe-maintainers:
    - matthiasdiener
